export const solarPanels =[
    {
        "id": 1,
        "brand": "Luminous",
        "model": "Polycrystalline 170W/12V",
        "material": "Polycrystalline",
        "power_wattage": 170,
        "efficiency": 15.5,
        "price": 6500,
        "temperature_coefficient": -0.38,
        "warranty_years": 25,
        "degradation_rate": 0.5,
        "voc": 23.01,
        "isc": 9.61,
        "low_light_performance": 85,
        "wind_snow_resistance": 5400,
        "installation_type": "Flat Roof, Slanted Roof",
        "width": 1.48,
        "height": 0.67
    },
    {
        "id": 2,
        "brand": "Navitas Solar",
        "model": "Navisol Series 320W",
        "material": "Polycrystalline",
        "power_wattage": 320,
        "efficiency": 17.1,
        "price": 12000,
        "temperature_coefficient": -0.45,
        "warranty_years": 10,
        "degradation_rate": 0.7,
        "voc": 45.2,
        "isc": 9.0,
        "low_light_performance": 80,
        "wind_snow_resistance": 5000,
        "installation_type": "Ground-Mount, Slanted Roof",
        "width": 1.95,
        "height": 1.0
    },
    {
        "id": 3,
        "brand": "UTL Solar",
        "model": "100W Polycrystalline",
        "material": "Polycrystalline",
        "power_wattage": 100,
        "efficiency": 15.0,
        "price": 4738,
        "temperature_coefficient": -0.41,
        "warranty_years": 25,
        "degradation_rate": 0.6,
        "voc": 21.6,
        "isc": 6.3,
        "low_light_performance": 78,
        "wind_snow_resistance": 4000,
        "installation_type": "Flat Roof, Portable",
        "width": 1.20,
        "height": 0.60
    },
    {
        "id": 4,
        "brand": "RenewSys",
        "model": "Deserv Series 340W",
        "material": "Monocrystalline",
        "power_wattage": 340,
        "efficiency": 18.0,
        "price": 13000,
        "temperature_coefficient": -0.39,
        "warranty_years": 25,
        "degradation_rate": 0.5,
        "voc": 37.65,
        "isc": 9.05,
        "low_light_performance": 82,
        "wind_snow_resistance": 5200,
        "installation_type": "Slanted Roof, Ground-Mount",
        "width": 2.00,
        "height": 1.0
    },
    {
        "id": 5,
        "brand": "Solar Technology",
        "model": "60W Crystalline",
        "material": "Monocrystalline",
        "power_wattage": 60,
        "efficiency": 14.5,
        "price": 26735,
        "temperature_coefficient": -0.42,
        "warranty_years": 20,
        "degradation_rate": 0.7,
        "voc": 17.2,
        "isc": 4.0,
        "low_light_performance": 75,
        "wind_snow_resistance": 3000,
        "installation_type": "Portable, Flat Roof",
        "width": 0.90,
        "height": 0.50
    },
    {
        "id": 6,
        "brand": "Luminous",
        "model": "Mono PERC 550W/24V",
        "material": "Monocrystalline",
        "power_wattage": 550,
        "efficiency": 21.0,
        "price": 17000,
        "temperature_coefficient": -0.30,
        "warranty_years": 25,
        "degradation_rate": 0.4,
        "voc": 49.80,
        "isc": 13.98,
        "low_light_performance": 90,
        "wind_snow_resistance": 6000,
        "installation_type": "Flat Roof, Slanted Roof",
        "width": 2.20,
        "height": 1.10
    },
    {
        "id": 7,
        "brand": "UTL Solar",
        "model": "400W Monocrystalline",
        "material": "Monocrystalline",
        "power_wattage": 400,
        "efficiency": 20.2,
        "price": 18837,
        "temperature_coefficient": -0.29,
        "warranty_years": 25,
        "degradation_rate": 0.3,
        "voc": 49.79,
        "isc": 10.31,
        "low_light_performance": 88,
        "wind_snow_resistance": 5500,
        "installation_type": "Slanted Roof, Ground-Mount",
        "width": 2.10,
        "height": 1.05
    },
    {
        "id": 8,
        "brand": "SunPower",
        "model": "Maxeon 3",
        "material": "Thin-Film",
        "power_wattage": 400,
        "efficiency": 22.6,
        "price": 35000,
        "temperature_coefficient": -0.26,
        "warranty_years": 25,
        "degradation_rate": 0.25,
        "voc": 69.5,
        "isc": 6.2,
        "low_light_performance": 92,
        "wind_snow_resistance": 5400,
        "installation_type": "Flat Roof, Slanted Roof",
        "width": 1.80,
        "height": 1.05
    },
    {
        "id": 9,
        "brand": "LG",
        "model": "NeON R",
        "material": "Monocrystalline",
        "power_wattage": 380,
        "efficiency": 21.4,
        "price": 32000,
        "temperature_coefficient": -0.30,
        "warranty_years": 25,
        "degradation_rate": 0.3,
        "voc": 66.8,
        "isc": 6.1,
        "low_light_performance": 88,
        "wind_snow_resistance": 5000,
        "installation_type": "Slanted Roof, Ground-Mount",
        "width": 1.90,
        "height": 1.00
    },
    { 
    "id": 10, 
    "brand": "Canadian Solar",
    "model": "HiKu 365", 
    "material": "Polycrystalline",
    "power_wattage": 365, 
    "efficiency": 20.2,
    "price": 28000, 
    "temperature_coefficient": -0.34, 
    "warranty_years": 20, 
    "degradation_rate": 0.35, 
    "voc": 67.5, 
    "isc": 5.8, 
    "low_light_performance": 85, 
    "wind_snow_resistance": 4500, 
    "installation_type": "Flat Roof, Ground-Mount", 
    "width": 1.95, 
    "height": 1.05
  },
    {
        "id": 11,
        "brand": "First Solar",
        "model": "Series 6",
        "material": "Thin-Film",
        "power_wattage": 420,
        "efficiency": 18.0,
        "price": 15000,
        "temperature_coefficient": -0.30,
        "warranty_years": 25,
        "degradation_rate": 0.5,
        "voc": 150.0,
        "isc": 3.5,
        "low_light_performance": 85,
        "wind_snow_resistance": 5400,
        "installation_type": "Ground-Mount, Flat Roof",
        "width": 2.00,
        "height": 1.20
    },
    {
        "id": 12,
        "brand": "JA Solar",
        "model": "JAM60S20 370/MR",
        "material": "Monocrystalline",
        "power_wattage": 370,
        "efficiency": 20.2,
        "price": 14000,
        "temperature_coefficient": -0.35,
        "warranty_years": 12,
        "degradation_rate": 0.55,
        "voc": 41.0,
        "isc": 11.0,
        "low_light_performance": 84,
        "wind_snow_resistance": 5400,
        "installation_type": "Slanted Roof, Ground-Mount",
        "width": 1.77,
        "height": 1.05
    },
    {
        "id": 13,
        "brand": "Trina Solar",
        "model": "Tallmax M 400W",
        "material": "Monocrystalline",
        "power_wattage": 400,
        "efficiency": 20.8,
        "price": 15500,
        "temperature_coefficient": -0.34,
        "warranty_years": 15,
        "degradation_rate": 0.5,
        "voc": 45.2,
        "isc": 10.2,
        "low_light_performance": 86,
        "wind_snow_resistance": 5400,
        "installation_type": "Flat Roof, Ground-Mount",
        "width": 2.00,
        "height": 1.00
    },
    {
        "id": 14,
        "brand": "JinkoSolar",
        "model": "Tiger Pro 530W",
        "material": "Monocrystalline",
        "power_wattage": 530,
        "efficiency": 21.3,
        "price": 18000,
        "temperature_coefficient": -0.35,
        "warranty_years": 12,
        "degradation_rate": 0.5,
        "voc": 49.5,
        "isc": 13.5,
        "low_light_performance": 87,
        "wind_snow_resistance": 5400,
        "installation_type": "Slanted Roof, Ground-Mount",
        "width": 2.20,
        "height": 1.10
    },
    {
        "id": 15,
        "brand": "REC Group",
        "model": "Alpha 370W",
        "material": "Monocrystalline",
        "power_wattage": 370,
        "efficiency": 21.7,
        "price": 14500,
        "temperature_coefficient": -0.26,
        "warranty_years": 25,
        "degradation_rate": 0.25,
        "voc": 38.0,
        "isc": 9.8,
        "low_light_performance": 90,
        "wind_snow_resistance": 7000,
        "installation_type": "Flat Roof, Slanted Roof",
        "width": 1.75,
        "height": 1.05
    },
    {
        "id": 16,
        "brand": "Panasonic",
        "model": "EverVolt 380W",
        "material": "Monocrystalline",
        "power_wattage": 380,
        "efficiency": 21.7,
        "price": 15000,
        "temperature_coefficient": -0.26,
        "warranty_years": 25,
        "degradation_rate": 0.26,
        "voc": 69.7,
        "isc": 6.3,
        "low_light_performance": 92,
        "wind_snow_resistance": 5400,
        "installation_type": "Flat Roof, Slanted Roof",
        "width": 1.80,
        "height": 1.05
    },
    {
        "id": 17,
        "brand": "Sharp",
        "model": "NU-JC410B",
        "material": "Monocrystalline",
        "power_wattage": 410,
        "efficiency": 20.5,
        "price": 16000,
        "temperature_coefficient": -0.34,
        "warranty_years": 15,
        "degradation_rate": 0.5,
        "voc": 49.0,
        "isc": 10.5,
        "low_light_performance": 85,
        "wind_snow_resistance": 5400,
        "installation_type": "Slanted Roof, Ground-Mount",
        "width": 1.85,
        "height": 1.00
    },
    {
        "id": 18,
        "brand": "Hanwha Q CELLS",
        "model": "Q.PEAK DUO-G9+ 390W",
        "material": "Monocrystalline",
        "power_wattage": 390,
        "efficiency": 20.8,
        "price": 14800,
        "temperature_coefficient": -0.34,
        "warranty_years": 25,
        "degradation_rate": 0.5,
        "voc": 41.8,
        "isc": 11.2,
        "low_light_performance": 88,
        "wind_snow_resistance": 5400,
        "installation_type": "Flat Roof, Slanted Roof",
        "width": 1.80,
        "height": 1.05
    }
]

 

   

 
